server:
  port: 8089
spring:
  application:
    name: product-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    #    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/products_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
springdoc:
  swagger-ui:
    path: /swagger-ui